<a href="https://colab.research.google.com/github/SaiDurga98/Machine-Learning/blob/main/nnModule_singleLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    # invokes the constructor pf parent class i.e.. nn module
    super().__init__()
    self.linear = nn.Linear(num_features, 1) # single neuron
    self.sigmoid = nn.Sigmoid() # Activation function

# forward pass
  def forward(self, features):
    output = self.linear(features) # z = wx + b
    output = self.sigmoid(output) # y_pred = sigmoid(z)
    return output


In [7]:
# Create dataset : # 10 rows, 5 columns (features -> 5 )
features = torch.rand(10,5)
# Create Model
model = Model(features.shape[1])
# call foward pass
#model.forward(features)
model(features)
# Output will be y_pred for 10 rows

tensor([[0.5522],
        [0.4877],
        [0.4934],
        [0.4206],
        [0.4469],
        [0.4602],
        [0.4356],
        [0.4529],
        [0.4894],
        [0.5518]], grad_fn=<SigmoidBackward0>)

In [9]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3111,  0.1350,  0.4146, -0.1948, -0.1105]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([-0.3811], requires_grad=True)